name: Build and deploy app with docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.1

      - name: Build and export Docker image
        run: bun run build

      - name: Change permissions of the tarball
        run: chmod 644 ./build/dfn-baker-street.tar

      - name: Upload image file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dfn-baker-street.tar
          path: build/dfn-baker-street.tar
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: dfn-baker-street.tar
          path: build

      - name: Transfer tarball and docker compose files to the server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: 'build/*.tar'
          target: '$HOME/baker-street'
          strip_components: 1

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd $HOME/baker-street
            docker stop baker-street
            docker rm baker-street
            docker load -i dfn-baker-street.tar
            docker run --env-file .env -d --name baker-street dfn-baker-street:1.0.0
